#!/bin/bash

echo "It's the captain!"

if git rev-parse --verify HEAD >/dev/null 2>&1
then
    against=HEAD
else
    # Initial commit: diff against an empty tree object
    against=$(git hash-object -t tree /dev/null)
fi

scriptSound="$(find . -type f -name '*sonorize*')"
status=0
for file in $(git diff --cached --name-only --diff-filter=AM "${against}")
do
    echo "${file}"
    if [ "$(sed -e '/^ *#/d' -e '/^ *$/d' "${file}" | wc -l)" -eq 0 ] ; then
        echo "Adding empty scripts to this repository is forbidden: ${file}"
        status=1
    fi

    if [[ "${file}" == *.sh || "$(file -b --mime-type "${file}")" = "text/x-shellscript" ]]; then 
        shellcheck "${file}"
        status=$?
    fi
done

if [ "${status}" == 1 ]; then
    soundStatus="error"
else
    soundStatus="ok"
fi
echo "${status}" "${soundStatus}"
"${scriptSound}" "${PWD}" "human" "${soundStatus}" &

exit "${status}"
